# Generated by Django 4.2.1 on 2024-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobject',
            name='data_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
